package com.libertyglobal.provisioning_asapvoice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.11
 * 2017-07-25T12:29:07.886+05:30
 * Generated source version: 2.6.11
 * 
 */
@WebServiceClient(name = "provisioning_ASAPVoice", 
                  wsdlLocation = "file:/F:/test/cox_repo/LGOSSAync/src/test/resources/WSDL/Provisioning_ASAPVoice.wsdl",
                  targetNamespace = "http://www.libertyglobal.com/provisioning_ASAPVoice") 
public class ProvisioningASAPVoice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.libertyglobal.com/provisioning_ASAPVoice", "provisioning_ASAPVoice");
    public final static QName PSNLProvisioningASAPVoiceSOAP = new QName("http://www.libertyglobal.com/provisioning_ASAPVoice", "PS_NL_Provisioning_ASAPVoice_SOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/test/cox_repo/LGOSSAync/src/test/resources/WSDL/Provisioning_ASAPVoice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProvisioningASAPVoice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/test/cox_repo/LGOSSAync/src/test/resources/WSDL/Provisioning_ASAPVoice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProvisioningASAPVoice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProvisioningASAPVoice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvisioningASAPVoice() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProvisioningASAPVoice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProvisioningASAPVoice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProvisioningASAPVoice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PSNLProvisioningASAPVoiceWS
     */
    @WebEndpoint(name = "PS_NL_Provisioning_ASAPVoice_SOAP")
    public PSNLProvisioningASAPVoiceWS getPSNLProvisioningASAPVoiceSOAP() {
        return super.getPort(PSNLProvisioningASAPVoiceSOAP, PSNLProvisioningASAPVoiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PSNLProvisioningASAPVoiceWS
     */
    @WebEndpoint(name = "PS_NL_Provisioning_ASAPVoice_SOAP")
    public PSNLProvisioningASAPVoiceWS getPSNLProvisioningASAPVoiceSOAP(WebServiceFeature... features) {
        return super.getPort(PSNLProvisioningASAPVoiceSOAP, PSNLProvisioningASAPVoiceWS.class, features);
    }

}
