package com.libertyglobal.provisioning_asapvoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.11
 * 2017-07-25T12:29:07.861+05:30
 * Generated source version: 2.6.11
 * 
 */
@WebService(targetNamespace = "http://www.libertyglobal.com/provisioning_ASAPVoice", name = "PS_NL_Provisioning_ASAPVoice_WS")
@XmlSeeAlso({com.libertyglobal.provisioning_asapvoice.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PSNLProvisioningASAPVoiceWS {

    @WebMethod(action = "provisioning_ASAPVoice")
    @WebResult(name = "provisioning_ASAPVoice_result", targetNamespace = "http://www.libertyglobal.com/Provisioning_ASAPVoice/Schema", partName = "parameters")
    public com.libertyglobal.provisioning_asapvoice.schema.ProvisioningASAPVoiceResult invoke(
        @WebParam(partName = "parameters", name = "provisioning_ASAPVoice", targetNamespace = "http://www.libertyglobal.com/Provisioning_ASAPVoice/Schema")
        com.libertyglobal.provisioning_asapvoice.schema.ProvisioningASAPVoice parameters
    );
}
